### ISSUE TITLE
Revisit installation wiki

### ISSUE THREAD

**Issue by zombah** [google/capirca#156]
After commit c5fd3cf simply running
```
$ python ./capirca/aclgen.py 
```
is not enough anymore, it returns:
```
Traceback (most recent call last):                  
  File "./capirca/aclgen.py", line 33, in <module>  
    from capirca.lib import aclgenerator                                                                 
ImportError: No module named capirca.lib
```
I found that setting Capirca folder to PYTHONPATH fixes this problem,
maybe wiki page need update now for new requirements?

**Comment by ankenyr** [comment]
PYTHONPATH isn't really the problem here. That is one thing you can do but since we are not packaging things trying to run is like that doesn't work. I am going to rename the title and try and work on this documentation. I just revamped the policy format with a small script to automatically output the tokens from _BuildTokens on each generator.

**Comment by starthir** [comment]
I can confirm the PYTHONPATH 'fixes' the issue, but looking forward to the updated documentation with instructions on how to use it without setting the env variable.

**Comment by ankenyr** [comment]
can you explain what you mean starthir?
Python path should not be an issue if you are installing this using setup.py or pip

**Comment by ankenyr** [comment]
Updated the installation page to show how to install from source and how to install from pip.

I don't believe PYTHONPATH is an issue here, please reopen if you want to continue that discussion or create a new issue.
