### ISSUE TITLE
Repository tags location in Juniper access list

### ISSUE THREAD

**Issue by michaltango** [google/capirca#176]
Is there a reason why repository tag for juniper generated access list file is located outside filter tag? 

https://github.com/google/capirca/blob/fa14b41f556e3995a372b473b11b1760947ee572/capirca/lib/juniper.py#L934

why following code:
```python
      for line in aclgenerator.AddRepositoryTags('** '):
        config.Append(line)
      config.Append('**')
```
couldn't be located after
```python
config.Append('filter %s {' % filter_name)
```` 

Wouldn't it be logical to have all information related to given filter within tag that it applies to?

**Comment by ankenyr** [comment]
The code is doing that, comments come above the section it applies to.

This is a term with a comment


```
/*
** This is the term comment
*/
term foo {
```

This is a filter with a comment

```
/*
** $Id:$
** $Date:$
** $Revision:$
**
** This is a filter comment
*/
filter bar {
```

Given that, I am unsure what your question is. I believe you are assuming that the filter tags should be coming after filter like the following

```
filter bar {
  /*
  ** $Id:$
  ** $Date:$
  ** $Revision:$
  **
  ** This is a filter comment
  */
  /*
  ** This is the term comment
  */
  term foo {
```

But that looks messy and weird to me. Even if we combined the comments why would we have some comments come before and some after. It is inconsistent.

**Comment by michaltango** [comment]
In my opinion this should be located within given filter from the beginning but moving it now could cause some compatibility issues if anyone is parsing these tags from current location. 
I would move entire comments section not only repository tags.

Giving example:
If you are dealing with configuration of thousand lines or more and want to get header details for given filter from within device CLI. What command would you use to do that?
`show configuration firewall family inet | match "\*\*|filter"`
Maybe that would work, but it's not clean or reliable.
Also parsing this information programmatically requires extra effort:
* Search for Repository tags in firewall/family/ section
* Search for next filter term and associate previously found tags etc

If you move it to within filter.
To list comment section for given filter:
`show configuration firewall family inet filter filter_name`
also programmatically it's easier to find. Just search for comments **within** given filter tag

Also it is worth mentioning that current state is not consistent compared to Cisco tag location which goes into access-list not before it.
you have:
```
ip access-list access-list-example
 remark some_comment
```
not 
```
!some comment
ip access-list access-list-example
```

(ignoring the fact that comment section (!) it will not be loaded to running configuration)

**Comment by ankenyr** [comment]
Maybe if you stated the problem you are trying to solve rather than an artifact of what is causing a problem it would lead to me being able to help you. Currently all I know is that you prefer to have the comments in a different location and provided an example that it would be cleaner to retrieve via the CLI but not what exactly you are doing.

To give an example of the difference, maybe the problem is that you want to ensure that all configs on the device are at the latest revision? If you are doing everything in some source control system, which I would assume since you are concerned with the tags, this should be easy to do. Keep all the outputs from Capirca in a directory and keep the live configs pulled from the devices in another directory. Check the live configs for the Id tags, map those back to the Capirca configs and make sure the revision number is the same. Anything that is not is out of date. You could also go crazier and do a string compare to make sure live configs are not getting changed on the device.
