### ISSUE TITLE
Juniper: only render term for given family

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#245]
Similarly to the `platform` term:
>  platform:: one or more target platforms for which this term should ONLY be rendered. *_platform-exclude:: one or more target platforms for which this term should NEVER be rendered.

It would be useful to be able to only generate a term for a given family (eg. ipv4 only term)

**Comment by SecurityForDotes** [comment]
Hiya,

Every generator should already include a mechanism to render for the correct address family. Usually in the filter options their are options like "inet, inet6, mixed", that would control what address family is used.

What platform are you trying and having issues with?

**Comment by XioNoX** [comment]
Platform is `Juniper`. There are options in the header, but not on a per term basis (as far as I know).
The idea is to use a policy with headers like:
```
header {
  target:: juniper myfilter4 inet
  target:: juniper myfilter6 inet6
}

So all both v4 and b6 filters stay in sync. Unfortunately we can have exceptions where a term should only be generated for v4 or 6.
For example if a server with both v4 and v6 IPs need to only be reachable over v4.
The current workaround is to have 2 policies with their respective header, but that requires to either have duplicated terms, or to use includes. For the latter the "snowflake" term can only be at the beginning or at the end of the terms (before or after the include).

**Comment by SecurityForDotes** [comment]
Ah totally my bad for mis-reading your request.

Given the way that capirca internal functions operate for address family, this change would be exceedingly difficult to implement in a consistent manner for every generator.

One method that could be feasible but feels a bit hacky would be to add the keyword to every term, and if that value matches the header type, process that term, otherwise skip.

So something like 
```
header {
  target:: juniper myfilter4 inet
}

term my-first-term {
  destination-address:: WEB_SERVERS
  protocol:: tcp
  action:: accept
  address_family: inet6
}

term my-second-term {
  destination-address:: WEB_SERVERS
  protocol:: udp
  action:: accept
  address_family: inet
}

term my-third-term {
  destination-address:: WEB_SERVERS
  protocol:: gre
  action:: accept
}
```
Would result in my-second-term and my-third-term (because no keyword being added) being rendered.  Essentially it is like an additional filter for each term to check address family, this would get a bit rough with mixed and the different way each generator implements it, but could be achieved.

let me talk to some more folks in the team to see what other says.

**Comment by SecurityForDotes** [comment]
So the team chatted about this and we think this could be of use for particular scenarios. There are a lot of hard edge cases that would need to handled across multiple generators regarding "mixed" address family.

 We would take a PR if you can provide one that solves the class of problems correctly for all generators.

**Comment by XioNoX** [comment]
What I had in mind was something like the above comment.
For example a term with `address_family: inet6` would not be rendered if the header have `inet` in it.
I can send a PR for Juniper, but I don't know any of the other generators. My guess is that other generators could implement it if the platform supports it (and if people need it).
One reason it's relevant to Juniper (and might not be for other platforms) is that Juniper has the concept of `source-prefix::` which references a list defined somewhere else.
Unfortunately a given list can only contain v4 or v6 IPs, not both. So the "magic" of Capirca's `destination-address::` (which automatically add the correct v4 or v6 IPs) doesn't apply here.
The end goal is to do:
```
term my-term6 {
  destination-prefix:: v6-only-prefixes
  protocol:: tcp
  action:: accept
  address_family: inet6
}

term my-term4 {
  destination-prefix:: v4-only-prefixes
  protocol:: tcp
  action:: accept
  address_family: inet
}
```
Where we use such lists (usually when the lists are also used in routing policies). And `destination-address` everywhere else.

Let me know if that's acceptable and I'll send a PR. Thanks

**Comment by XioNoX** [comment]
@SecurityForDotes hi, what do you think about the comment above? I can work on a PR if it's the good direction. Thanks

**Comment by abhindes** [comment]
Hi,

Just to make sure I understand correctly, the potential PR for this issue hinges on the [PR adding support for multiple targets in Juniper](https://github.com/google/capirca/pull/266), correct?

**Comment by XioNoX** [comment]
That's correct, it would be useful in that use-case.

**Comment by abhindes** [comment]
(Just for continuity, I'm also having the conversation here) 

Thanks for your work on #266, please see my comment on https://github.com/google/capirca/pull/266#issuecomment-840854699 

Once we have resolved that conversation, we can get back to this, which is the usage of "address_family" within a term to specify that this is only meant to be rendered only for a specific family. 

I think we can continue with this form of implementation, but we would highly recommend implementing this for more than one generator than just Juniper. This is because we don't prefer singleton behavior, where a keyword/token only works for a single generator (unless it is dictated by the vendor). Please let us know if this is something you'd be able to work towards. It doesn't have to be all generators, but at least a few of the common used generators where this might be useful (such as Cisco, Arista, JuniperSRX etc). 

But I think it's important to first resolve #266 since this Issue depends on that.

**Comment by nero85** [comment]
This was merged and fixed. Closing issue.
