### ISSUE TITLE
Juniper: add filter term/action

### ISSUE THREAD

**Issue by XioNoX** [google/capirca#246]
In Juniper firewall filters, a term can reference a different filter:
```
filter filter1 {
  term my-term {
      filter filter2;
  }
}
filter filter2 {
...
}
```
We use this as some of our filters have specific Jinja templates applied to them, which we can't reproduce with Capirca.

Our current workaround is to use the `verbatim::` term, but as the doc says it should be temporary until it's natively supported.

**Comment by abhindes** [comment]
This is a reasonable ask, since we want to directly support commonly used features of a vendor platform, and not via verbatim.

This would probably be a keyword "filter" that could be specified in that term, take an input string, and then the output would have that string. This seems simple to implement as well. Would you like to create a PR for this?

**Comment by XioNoX** [comment]
Thanks for your reply. It's on my radar, but not sure when I'll have time for a PR.

**Comment by abhindes** [comment]
Feel free to create a PR when you can. If I get the time in the next few days, I'll create this since it should be simple enough.

**Comment by abhindes** [comment]
#263 has been merged. Closing this issue out.
