### ISSUE TITLE
dynamic generation of definitions via python API

### ISSUE THREAD

**Issue by 991jo** [google/capirca#250]
Is it possible to dynamically generate definitions instead of loading them from a file? I have to generate a lot of ACLs that follow the same basic policy, just with different networks in some sections. All those networks come from my source of truth and I dont want to create several hundred, may even thousands of definitions, keep them up to date and track them in a git repo. Instead I would prefer to load my basic definitions, add the ones I need to build the policy I want to build and then build the policy.

Is there a (officially supported) way to do this? Of course I could start hacking around in the data structures at runtime, but since that is probably not intended I would have to patch my stuff every now and then, when some internal representations change.

**Comment by greenpau** [comment]
> Is it possible to dynamically generate definitions instead of loading them from a file?

@991jo , capirca does not do that. What would be the logic for the dynamic generation? i.e. what would be the abstract you would provide to capirca?

For example, here is what I imagined after reading your ask.

```
TACACS_SERVERS = load("https://api_endpoint/servers/tacacs")

/or

TACACS_SERVERS = load("script", "/path/to/script.py", "arg1", "arg2")
```

You?

**Comment by 991jo** [comment]
I was thinking of something that works via the python API:
```
from capirca.lib import naming
defs = naming.Naming('./def')  # load some static definitions

# add a new definition via python
tacacs_server = ["2001:db8::1/128", "10.21.42.123/32"]
defs.networks.add("TACACS_SERVERS", tacacs_servers)

# add the remaining policy loading and rendering logic here
```

**Comment by ankenyr** [comment]
Naming.py was never meant to pull from a live API. There was at one point a file included called [definate.py](https://github.com/google/capirca/blob/0ec49067ecf09c3c9fc616f9ff738e533962bcc6/definate.py) which would pull down IPs from sources. The only one we made public was DNS as all of the ones we use internally are Google specific. The reasoning for something like definate but not something like you are suggesting is version control. We wished to be able to rebuild or roll back to old versions if neccesary.

**Comment by 991jo** [comment]
From the "I want to roll back everything with my version control" point of view this is fine.
If you use what I am thinking about then you would of course loose that, but if you don't your roll back capability is not affected.

I haven't looked to deep into the code yet, but is there anything that would prevent me from implementing that?
Would people be willing to merge a feature like this?

**Comment by ankenyr** [comment]
Without a clear design of how this would be implemented I would hesitate including a feature like this. There are a bunch of issues I could see croping up that I don't have good ideas on how to resolve. How do we go about writing out multiple files each with the slight differences in IPs? It is currently a 1:1 or 1:2 mapping, both of which is explicitly set. How do we express this in the policy file itself? Do we add some token such as `TACAC_SERVER % 2` to say take two of the IP addresses? What happens if there is another rule with the same thing? Does it get permuted? For version control how do we make sure that each file outputted is of similar versioning?

I could write more but I think you get the point. There is a lot to think about here which may be very unique to your own specific environment. It has always been my opinion that what people come to Capirca for are the generators and other files in lib. The file aclgen.py is nice but rather simple. If it works for your environment, that is great but it likely doesn't work for everyone. In those cases you should be integrating the generators, policy.py, and naming.py into your pipeline. If I ever left Google and was tasked with ACL management again this is what I would do.

@greenpau I will leave this up to you, @rdsharma and @SecurityForDotes  to discuss. Happy to let you all pick my brain more on this topic if you wish for more context on anything.

**Comment by rdsharma** [comment]
We discussed this in a meeting today and agree with what @ankenyr said previously. We do appreciate your willingness to contribute this feature but I don't think this is something we'd like to support in Capirca right now. As Rob said, a lot of details will be specific to how you want to integrate into your environment. In addition, supporting object-level modification of inner Capirca structures wasn't intended at the beginning and it'd probably take a lot of work to make sure that these modifications always have the intended effect (and likely would result in a lot of corner case bugs as well).

Like Rob said, we recommend working the generators, policy lib, naming lib, etc into your pipeline as you see fit. This should allow whatever flexibility you want while still using Capirca for rendering vendor syntax.

Going to close this one now, thanks!

**Comment by 991jo** [comment]
Yeah, I think this can be closed. Somehow I have not seen that `naming` has the methods `ParseNetworkList()` and `ParseServiceList()`. Those do what I need. Having "public" access to `_CheckUnseen()` would be nice, but I can work my way around that. Sorry for the noise.
