### ISSUE TITLE
Cisco extended ACL sequence number and log option

### ISSUE THREAD

**Issue by Swanfir** [google/capirca#90]
Hi,
maybe I have not read deep enough...

Please add the opportunity for sequence numbers and log option  in Cisco  ACLs. Or  a short noob intro in which script(s) these functions have to be defined and I give it a try.

**Comment by ankenyr** [comment]
Hi @Swanfir 
Logging is already an option, please see the wiki pages on policy format.

By sequence numbers I am assuming you mean [this](http://www.cisco.com/c/en/us/td/docs/ios/12_2s/feature/guide/fsaclseq.html#wp1042954)?
If so I don't think this is necessary or desired. In Capirca you have a policy file which describes how you want your firewall to behave regardless of the platform. When you need to add a new rule you insert that into the correct place in the policy file and render the syntax again. You take this output and apply it to the  firewall. Sequence nubmers were made so that you could easily insert a single rule into the firewall. Capirca you reapply everything.

**Comment by Swanfir** [comment]
Ok got it. 
I was looking to much from Cisco point of view and not of multi vendor view.
And for logging:
logging:: supported juniper, srx and iptables/speedway, specify that this packet should be logged via syslog
 I read it as CISCO excluded and did not try logging:: syslog
Thanks for the hints.
